language: node_js

node_js:
  - "5.0.0"

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c "CREATE USER wortopia WITH PASSWORD 'wortopia';" -U postgres
  - psql -c 'CREATE DATABASE wortopia_test WITH OWNER wortopia;' -U postgres
  - psql -d wortopia_test -c 'CREATE EXTENSION IF NOT EXISTS citext;' -U postgres
  - psql -d wortopia_test -c 'CREATE EXTENSION IF NOT EXISTS pgcrypto;' -U postgres
  - psql -d wortopia_test -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres
