language: node_js

node_js:
  - "0.12"
  - "4.0.0"
  - "5.0.0"
  - "stable"

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database wortopia_test;' -U postgres