// Generated by CoffeeScript 1.3.1

/*
	Requires socket.io and jQuery
*/


(function() {
  var htmlEntities;

  htmlEntities = function(str) {
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  };

  $(function() {
    var socket;
    socket = io.connect('http://localhost:8080');
    socket.on('gameTime', function(gameID, gameTime) {
      return console.log(gameID, gameTime);
    });
    socket.emit('identify', 'sessionid');
    /*
    	Chat
    */

    $('#chat_input').keypress(function(e) {
      var code, _ref;
      code = (_ref = e.keyCode) != null ? _ref : e.which;
      if (code === 13) {
        socket.emit('chat', $('#chat_input').val());
        return $('#chat_input').val('');
      }
    });
    return socket.on('chat', function(user, message) {
      var username;
      username = htmlEntities(user.name);
      message = htmlEntities(message);
      return $('#chat_display').append("<div><b>" + username + " :</b>" + message + "</div>");
    });
  });

}).call(this);
