name: build-and-deploy-wortopia
on:
  push:
  schedule:
    - cron: '0 1 * * *' # at 1am every night
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: run ./github-action.sh on host
        uses: appleboy/ssh-action@master
        with:
         host: wortopia.de
         username: wortopia
         key: ${{ secrets.SSH_KEY }}
         script: |
          cd wortopia-node
          git pull --rebase
          ./github-action.sh
